version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    ports:
      - 3306:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db/:/database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    driver: bridge
    name: psql